# Generated by Django 5.0.6 on 2024-07-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_orderline_decorations_orderline_decorations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.orderline'),
        ),
    ]
