# Generated by Django 5.0.6 on 2024-07-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_order_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='decorations',
        ),
        migrations.AddField(
            model_name='orderline',
            name='decorations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.decorations'),
        ),
    ]
