# Generated by Django 5.0.6 on 2024-07-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_orderline_order_alter_order_deco_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deco_qty',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='decorations_qty',
            field=models.IntegerField(default=0, verbose_name='Decorations Quantity'),
        ),
    ]
