# Generated by Django 5.0.6 on 2024-07-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_order_product_remove_order_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='silk_id',
            new_name='color',
        ),
    ]
