# Generated by Django 5.0.6 on 2024-07-09 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_silk_id_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='decorations',
        ),
        migrations.RemoveField(
            model_name='order',
            name='decorations_qty',
        ),
        migrations.AddField(
            model_name='orderline',
            name='dec_qty',
            field=models.IntegerField(default=0, verbose_name='Decorations Quantity'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='decorations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.decorations'),
        ),
    ]
