# Generated by Django 5.0.6 on 2024-07-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_order_decorations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorations',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='decorations',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='decorations',
            name='remaining',
            field=models.IntegerField(default=0, verbose_name='Remaining'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='remaining',
            field=models.IntegerField(default=0, verbose_name='Remaining'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='silk',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='silk',
            name='remaining',
            field=models.IntegerField(default=0, verbose_name='Remaining'),
        ),
    ]
