# Generated by Django 5.0.6 on 2024-07-09 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_order_dec_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dec_price',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='dec_qty',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='decorations',
        ),
        migrations.CreateModel(
            name='DecorationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_qty', models.IntegerField(default=0, verbose_name='Decorations Quantity')),
                ('decorations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.decorations')),
            ],
        ),
    ]
