# Generated by Django 5.0.6 on 2024-07-09 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_order_dec_price_remove_orderline_dec_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorationline',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
        ),
    ]
