# Generated by Django 5.0.6 on 2024-07-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decorations_cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.decorations')),
                ('materials_cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.materials')),
                ('order_total', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
                ('product_cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
