# Generated by Django 5.0.6 on 2024-07-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_profit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profit',
        ),
    ]
