# Generated by Django 5.0.6 on 2024-07-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_order_wrapping_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrappingPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_qty', models.IntegerField(default=0, verbose_name='Wrapping paper quantity')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
                ('wrapping_paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.materials')),
            ],
        ),
    ]
