# Generated by Django 5.0.6 on 2024-07-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_wrappingpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='materials_remaining',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.materials'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='silk_remaining',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.silk'),
        ),
        migrations.AddField(
            model_name='silk',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
        ),
    ]
