# Generated by Django 5.0.6 on 2024-07-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_orderline_materials_remaining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silk',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='silk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.silk'),
        ),
    ]
