# Generated by Django 5.0.6 on 2024-07-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_silk_order_order_silk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='silk',
        ),
        migrations.AddField(
            model_name='silk',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
        ),
    ]
