# Generated by Django 5.0.6 on 2024-07-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_remove_order_silk_silk_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silk',
            name='remaining',
            field=models.FloatField(default=0, verbose_name='Remaining'),
        ),
    ]
