# Generated by Django 5.0.6 on 2024-07-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_silk_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='qty',
            field=models.FloatField(default=0, verbose_name='Quantity'),
        ),
    ]
