# Generated by Django 5.0.6 on 2024-07-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_orderline_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='materials_remaining',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='silk_remaining',
        ),
        migrations.RemoveField(
            model_name='silk',
            name='order',
        ),
    ]
